LZW Compressor: EncoderDictionary Class Reference
EncoderDictionary Class Reference
Encoder's custom dictionary type.
Classes
struct Node
Binary search tree node.
Public Member Functions
EncoderDictionary ()
Default constructor.
void reset ()
Resets dictionary to its initial contents.
CodeType search_and_insert (CodeType i, char c)
Searches for a pair (i, c) and inserts the pair if it wasn't found.
CodeType search_initials (char c) const
Fakes a search for byte c in the one-byte area of the dictionary.
Private Attributes
std::vector< Node > vn
Vector of nodes on top of which the binary search tree is implemented.
std::array< CodeType, 1u<< CHAR_BIT > initials
Cheat sheet for mapping one-byte strings to their codes.
Detailed Description
Encoder's custom dictionary type.
Definition at line 53 of file lzw_v5.cpp.
Constructor & Destructor Documentation
EncoderDictionary::EncoderDictionary () inline
Default constructor.
It builds the initials cheat sheet.
Definition at line 80 of file lzw_v5.cpp.
References initials, reset(), and vn.
     {
         const long int minc = std::numeric_limits<char>::min();
         const long int maxc = std::numeric_limits<char>::max();
         CodeType k {0};
         for (long int c = minc; c <= maxc; ++c)
             initials[static_cast<unsigned char> (c)] = k++;
         vn.reserve(globals::dms);
         reset();
     }
Member Function Documentation
void EncoderDictionary::reset () inline
Resets dictionary to its initial contents.
See Also
EncoderDictionary::EncoderDictionary()
Definition at line 97 of file lzw_v5.cpp.
References vn.
Referenced by EncoderDictionary(), and search_and_insert().
     {
         vn.clear();
         const long int minc = std::numeric_limits<char>::min();
         const long int maxc = std::numeric_limits<char>::max();
         for (long int c = minc; c <= maxc; ++c)
             vn.push_back(Node(c));
     }
CodeType EncoderDictionary::search_and_insert (CodeType i, char c) inline
Searches for a pair (i, c) and inserts the pair if it wasn't found.
Parameters
i code to search for
c attached byte to search for
Returns
The index of the pair, if it was found.
Return values
globals::dms if the pair wasn't found
Definition at line 115 of file lzw_v5.cpp.
References reset(), search_initials(), and vn.
Referenced by compress().
     {
         // dictionary's maximum size was reached
         if (vn.size() == globals::dms)
             reset();
         if (i == globals::dms)
             return search_initials(c);
         const CodeType vn_size = vn.size();
         CodeType ci {vn[i].first}; // Current Index
         if (ci != globals::dms)
         {
             while (true)
                 if (c < vn[ci].c)
                 {
                     if (vn[ci].left == globals::dms)
                     {
                         vn[ci].left = vn_size;
                         break;
                     }
                     else
                         ci = vn[ci].left;
                 }
                 else
                 if (c > vn[ci].c)
                 {
                     if (vn[ci].right == globals::dms)
                     {
                         vn[ci].right = vn_size;
                         break;
                     }
                     else
                         ci = vn[ci].right;
                 }
                 else // c == vn[ci].c
                     return ci;
         }
         else
             vn[i].first = vn_size;
         vn.push_back(Node(c));
         return globals::dms;
     }
CodeType EncoderDictionary::search_initials (char c) const inline
Fakes a search for byte c in the one-byte area of the dictionary.
Parameters
c byte to search for
Returns
The code associated to the searched byte.
Definition at line 166 of file lzw_v5.cpp.
References initials.
Referenced by compress(), and search_and_insert().
     {
         return initials[static_cast<unsigned char> (c)];
     }
The documentation for this class was generated from the following file:
lzw_v5.cpp