case1: case1_register_move.cpp
	g++ -o case1 case1_register_move.cpp

case2: case2_L1_move.cpp
	g++ -o case2 case2_L1_move.cpp

case3: case3_LLC_move.cpp
	g++ -o case3 case3_LLC_move.cpp

all: case1 case2 case3
